name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Install Web app dependencies
        run: npm install
        working-directory: apps/web

      - name: Install API dependencies
        run: npm install
        working-directory: apps/api

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install concurrently and wait-on
        run: npm install -D concurrently wait-on

      - name: Run tests with servers
        run: |
          npx concurrently -k -s first \
            "cd apps/api && npm run dev" \
            "cd apps/web && npm run dev" \
            "npx wait-on http://localhost:3333 http://localhost:8080 && npx playwright test"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
